export const INITIAL_PLANETS = {
  planets: {
    aboutMe: {
      orbitRadius: 20,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 5,
      classList: "planets__aboutMe",
    },
    education: {
      orbitRadius: 29,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 3,
      classList: "planets__education",
    },
    skills: {
      orbitRadius: 39,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 7,
      classList: "planets__skills",
    },
    projects: {
      orbitRadius: 50,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 4,
      classList: "planets__projects",
    },
    contact: {
      orbitRadius: 65,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 2,
      classList: "planets__contact",
    },
    languages: {
      orbitRadius: 73,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 8,
      classList: "planets__languages",
    },
    awards: {
      orbitRadius: 82,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 6,
      classList: "planets__awards",
    },
    interests: {
      orbitRadius: 90,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 3,
      classList: "planets__interests",
    },
    experience: {
      orbitRadius: 100,
      rotationPeriod: 10,
      orbitalPeriod: 10,
      diameter: 6,
      classList: "planets__experience",
    },
  },
}
