export const parallaxInitialState = [
  {
    id: 1,
    name: "cloud-dark",
    src: "/images/parallaxImages/cloud-dark.png",
    classList: "cloud-dark no-select",
    strength: 0.04,
    zIndex: null,
    lerpEase: 0.01,
  },
  {
    id: 2,
    name: "cloud-light",
    src: "/images/parallaxImages/cloud-light.png",
    classList: "cloud-light no-select",
    strength: 0.02,
    zIndex: null,
    lerpEase: 0.04,
  },
  {
    id: 3,
    name: "cloud-large",
    src: "/images/parallaxImages/cloud-large.png",
    classList: "cloud-large no-select",
    strength: 0.02,
    zIndex: null,
    lerpEase: 0.015,
  },
  {
    id: 4,
    name: "cloud-red",
    src: "/images/parallaxImages/cloud-red.png",
    classList: "cloud-red no-select",
    strength: 0.03,
    zIndex: null,
    lerpEase: 0.002,
  },
  {
    id: 5,
    name: "cloud-oval",
    src: "/images/parallaxImages/cloud-oval.png",
    classList: "cloud-oval no-select",
    strength: 0.004,
    zIndex: null,
    lerpEase: 0.05,
  },
  {
    id: 6,
    name: "small-objects",
    src: "/images/parallaxImages/small-objects.png",
    classList: "small-objects no-select",
    strength: 0.015,
    zIndex: null,
    lerpEase: 0.2,
  },
]
